site_name: "Dubhe"

form_fields:
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"
  category: "type"
  tags[4][]: "tags[]"

source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"

  standard_keys:
    type:
      "Movies": "category.movie"
      "TV Series": "category.tv_series"
      "TV Shows": "category.tv_shows"
      "Documentaries": "category.documentaries"
      "Animations": "category.animation"
      "Music Videos": "category.mv"
      "Sports": "category.sports"
      "HQ Audio": "category.music"
      "Misc": "category.other"
      "Books": "category.books"
      "photo": "category.photo"

    medium:
      "Track": "medium.track"
      "CD": "medium.cd"
      "DVDR": "medium.dvdr"
      "HDTV": "medium.hdtv"
      "MiniBD": "medium.minibd"
      "Encode": "medium.encode"
      "Remux": "medium.remux"
      "HD DVD": "medium.hddvd"
      "Blu-ray": "medium.bluray"
      "WEB-DL": "medium.webdl"

    video_codec:
      "H.265/HEVC": "video.h265"
      "x.265": "video.x265"
      "H.264/AVC": "video.h264"
      "x264": "video.x264"
      "MPEG-4": "video.mpeg4"
      "MPEG-2": "video.mpeg2"
      "VC-1": "video.vc1"
      "AV1": "video.av1"
      "Xvid": "video.xvid"
      "Other": "video.other"

    resolution:
      "2160p/2160i": "resolution.r2160p"
      "1080p/1080i": "resolution.r1080p"
      "720p": "resolution.r720p"
      "SD": "resolution.sd"
      "Other/其他": "resolution.other"

    team:
      "HDS": "team.hds"
      "CHD": "team.chd"
      "MySiLU": "team.mysilu"
      "WiKi": "team.wiki"
      "Other": "team.other"
      "DubheWeb": "team.dubheweb"

mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "402"
    "category.tv_shows": "403"
    "category.documentaries": "404"
    "category.animation": "405"
    "category.mv": "406"
    "category.sports": "407"
    "category.music": "408"
    "category.other": "409"
    "category.books": "410"
    "category.photo": "411"
    "default": "401"

  medium:
    "medium.track": "9"
    "medium.cd": "8"
    "medium.dvdr": "6"
    "medium.hdtv": "5"
    "medium.minibd": "4"
    "medium.encode": "7"
    "medium.remux": "3"
    "medium.hddvd": "2"
    "medium.bluray": "1"
    "medium.webdl": "10"
    "default": "10"

  video_codec:
    "video.h265": "11"
    "video.x265": "10"
    "video.h264": "13"
    "video.x264": "12"
    "video.mpeg4": "7"
    "video.mpeg2": "6"
    "video.vc1": "2"
    "video.av1": "9"
    "video.xvid": "8"
    "video.other": "5"
    "default": "5"

  resolution:
    "resolution.r2160p": "5"
    "resolution.r1080p": "1"
    "resolution.r720p": "3"
    "resolution.sd": "4"
    "resolution.other": "7"
    "default": "7"

  team:
    "team.hds": "1"
    "team.chd": "2"
    "team.mysilu": "3"
    "team.wiki": "4"
    "team.other": "5"
    "team.dubheweb": "6"
    "default": "5"

  tag:
    "tag.DIY": 4
    "tag.国语": 5
    "tag.中字": 6
    "tag.HDR": 7
    "default": null
