# HDTime站点的配置文件
# 基于三层解耦模型重构，包含source_parsers和标准化的mappings

site_name: "HDTime"

# 表单字段定义 - 定义站点上传表单中各字段的标识符
form_fields:
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  team: "team_sel[4]"
  category: "type" # 类别字段映射到type参数

# 标准化键映射 - 定义源文本到标准化键的映射规则
# source_parsers部分：定义如何从原始数据解析出标准化参数
source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    audio_codec:
      source_key: "音频编码"
    team:
      source_key: "制作组"

  # 标准化键映射规则（从原始文本到标准化键）
  standard_keys:
    type:
      "电影": "category.movie"
      "剧集": "category.tv_series"
      "综艺": "category.tv_shows"
      "纪录片": "category.documentaries"
      "动漫": "category.animation"
      "MV": "category.mv"
      "音乐": "category.music"
      "体育": "category.sports"
      "软件": "category.software"
      "游戏": "category.game"
      "文档": "category.document"
      "其他": "category.other"
      "Blu-Ray原盘": "category.blu_ray"

    medium:
      "Blu-ray": "medium.bluray"
      "Remux": "medium.remux"
      "Encode": "medium.encode"
      "WEB-DL": "medium.webdl"
      "HDTV": "medium.hdtv"
      "MiniBD": "medium.minibd"
      "HD DVD": "medium.hddvd"
      "DVDR": "medium.dvdr"
      "CD": "medium.cd"
      "Track": "medium.track"
      "Other": "medium.other"

    video_codec:
      "AVC/H.264/x264": "video.h264"
      "HEVC/H.265/x265": "video.h265"
      "x264-10bit": "video.x264_10bit"
      "AV1": "video.av1"
      "VP8/VP9": "video.vp9"
      "AVS3": "video.avs3"
      "xvid": "video.xvid"
      "MPEG-2": "video.mpeg2"
      "VC-1": "video.vc1"
      "VVC/H.266/x266": "video.h266"
      "Other": "video.other"

    audio_codec:
      "TrueHD Atmos": "audio.truehd_atmos"
      "TrueHD": "audio.truehd"
      "DTS-HD": "audio.dts_hd"
      "DTS": "audio.dts"
      "DD/AC3": "audio.ac3"
      "DDP/EAC3": "audio.ddp"
      "LPCM/PCM": "audio.lpcm"
      "AAC": "audio.aac"
      "Audio Vivid/AV3A": "audio.audio_vivid"
      "OPUS": "audio.opus"
      "FLAC": "audio.flac"
      "APE": "audio.ape"
      "MP3": "audio.mp3"
      "OGG": "audio.ogg"
      "Other": "audio.other"

    team:
      "个人原创": "team.personal"
      "Other": "team.other"
      "CHD": "team.chd"
      "beAst": "team.beast"
      "WiKi": "team.wiki"
      "CMCT": "team.cmct"
      "PADTime": "team.padtime"
      "VTime": "team.vtime"
      "HDT": "team.hdt"
      "HDTime": "team.hdtime"
      "QHstudIo": "team.qhstudio"
      "AilMWeb": "team.ailmweb"
      "HHWEB": "team.hhweb"

# 参数映射规则 - 定义如何将标准化键映射到站点特定参数
mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "402"
    "category.tv_shows": "403"
    "category.documentaries": "404"
    "category.animation": "405"
    "category.mv": "406"
    "category.music": "408"
    "category.sports": "407"
    "category.software": "414"
    "category.game": "410"
    "category.document": "411"
    "category.other": "409"
    "category.blu_ray": "424"
    "default": "401"

  medium:
    "medium.bluray": "1"
    "medium.remux": "3"
    "medium.encode": "7"
    "medium.webdl": "10"
    "medium.hdtv": "5"
    "medium.minibd": "4"
    "medium.hddvd": "2"
    "medium.dvdr": "6"
    "medium.cd": "8"
    "medium.track": "9"
    "medium.other": "13"
    "default": "13"

  video_codec:
    "video.h264": "1"
    "video.h265": "12"
    "video.x264_10bit": "11"
    "video.av1": "15"
    "video.vp9": "14"
    "video.avs3": "17"
    "video.xvid": "3"
    "video.mpeg2": "4"
    "video.vc1": "2"
    "video.h266": "16"
    "video.other": "5"
    "default": "5"

  audio_codec:
    "audio.truehd_atmos": "8"
    "audio.truehd": "9"
    "audio.dts_hd": "10"
    "audio.dts": "3"
    "audio.ac3": "11"
    "audio.ddp": "12"
    "audio.lpcm": "13"
    "audio.aac": "6"
    "audio.audio_vivid": "14"
    "audio.opus": "15"
    "audio.flac": "1"
    "audio.ape": "2"
    "audio.mp3": "4"
    "audio.ogg": "5"
    "audio.other": "7"
    "default": "7"

  team:
    "team.personal": "9"
    "team.other": "5"
    "team.chd": "2"
    "team.beast": "3"
    "team.wiki": "4"
    "team.cmct": "8"
    "team.padtime": "7"
    "team.vtime": "15"
    "team.hdt": "12"
    "team.hdtime": "6"
    "team.qhstudio": "16"
    "team.ailmweb": "17"
    "team.hhweb": "18"
    "default": "5"

  tag:
    "tag.杜比视界": 8
    "tag.禁转": 1
    "tag.DIY": 4
    "tag.国语": 5
    "tag.中字": 6
    "tag.HDR": 7
    "default": null
