site_name: "TangPT"

form_fields:
  category: "type"
  medium: "medium_sel[4]"
  video_codec: "codec_sel[4]"
  audio_codec: "audiocodec_sel[4]"
  resolution: "standard_sel[4]"
  team: "team_sel[4]"
  tags: "tags[4][]"

source_parsers:
  source_params:
    type:
      source_key: "类型"
    medium:
      source_key: "媒介"
    video_codec:
      source_key: "视频编码"
    audio_codec:
      source_key: "音频编码"
    resolution:
      source_key: "分辨率"
    team:
      source_key: "制作组"

  standard_keys:
    type:
      "电影": "category.movie"
      "电视剧": "category.tv_series"
      "综艺": "category.tv_shows"
      "纪录片": "category.documentaries"
      "动漫": "category.animation"
      "MV": "category.mv"
      "体育": "category.sports"
      "HQ音频": "category.hq_audio"
      "音乐": "category.music"
      "书籍": "category.books"
      "其他": "category.other"
      "短剧": "category.micro_drama"

    medium:
      "Track": "medium.track"
      "CD": "medium.cd"
      "DVDR": "medium.dvdr"
      "HDTV": "medium.hdtv"
      "MiniBD": "medium.minibd"
      "Encode": "medium.encode"
      "Remux": "medium.remux"
      "HD DVD": "medium.hddvd"
      "Blu-ray": "medium.bluray"
      "UHD Blu-ray": "medium.uhd_bluray"
      "WEB-DL": "medium.webdl"

    video_codec:
      "H.264/AVC": "video.h264"
      "H.265/HEVC": "video.h265"
      "AV1": "video.av1"
      "VP8/9": "video.vp9"
      "VC-1": "video.vc1"
      "Xvid": "video.xvid"
      "MPEG-2": "video.mpeg2"
      "Other": "video.other"

    audio_codec:
      "TrueHD Atmos": "audio.truehd_atmos"
      "DTS-HD MA": "audio.dtshd_ma"
      "DTS:X": "audio.dtsx"
      "DTS": "audio.dts"
      "TrueHD": "audio.truehd"
      "LPCM": "audio.lpcm"
      "WAV": "audio.wav"
      "FLAC": "audio.flac"
      "DD/AC3": "audio.ac3"
      "DDP/E-AC3": "audio.ddp"
      "AAC": "audio.aac"
      "OGG": "audio.ogg"
      "MP3": "audio.mp3"
      "M4A": "audio.m4a"
      "OPUS": "audio.opus"
      "APE": "audio.ape"
      "AV3V": "audio.av3v"
      "Other": "audio.other"

    resolution:
      "1080i/1080P": "resolution.r1080p"
      "2K/1440i/1440P": "resolution.r1440p"
      "4K/2160i/2160P": "resolution.r2160p"
      "8K/4320i/4320P": "resolution.r4320p"
      "720i/720P": "resolution.r720p"
      "480i/480P": "resolution.r480p"
      "Other": "resolution.other"

    team:
      "QHstudIo": "team.qhstudio"
      "CHD": "team.chd"
      "HDS": "team.hds"
      "CSPT": "team.cspt"
      "UBWEB": "team.ubweb"
      "ZmWeb": "team.zmweb"
      "HHWEB": "team.hhweb"
      "ADWeb": "team.adweb"
      "U2": "team.u2"
      "OpenCD": "team.opencd"
      "beAst": "team.beast"
      "HDArea": "team.hdarea"
      "FFansDIY": "team.ffansdiy"
      "CMCT": "team.cmct"
      "OurTV": "team.ourtv"
      "BtsHD": "team.btshd"
      "HDHome": "team.hdhome"
      "PTerWEB": "team.pterweb"
      "HDSWEB": "team.hdsweb"
      "MWeb": "team.mweb"
      "FRDS": "team.frds"
      "AGSVWEB": "team.agsvweb"
      "StarfallWeb": "team.starfallweb"
      "WiKi": "team.wiki"
      "MySiLU": "team.mysilu"
      "Other": "team.other"

mappings:
  type:
    "category.movie": "401"
    "category.tv_series": "402"
    "category.tv_shows": "403"
    "category.documentaries": "404"
    "category.animation": "405"
    "category.mv": "406"
    "category.sports": "407"
    "category.hq_audio": "408"
    "category.music": "409"
    "category.books": "410"
    "category.other": "411"
    "category.micro_drama": "412"
    "default": "411"

  medium:
    "medium.track": "9"
    "medium.cd": "8"
    "medium.dvdr": "6"
    "medium.hdtv": "5"
    "medium.minibd": "4"
    "medium.encode": "7"
    "medium.remux": "3"
    "medium.hddvd": "2"
    "medium.bluray": "1"
    "medium.uhd_bluray": "10"
    "medium.webdl": "11"
    "default": "7"

  video_codec:
    "video.h264": "1"
    "video.h265": "6"
    "video.av1": "7"
    "video.vp9": "10"
    "video.vc1": "2"
    "video.xvid": "3"
    "video.mpeg2": "4"
    "video.other": "5"
    "default": "5"

  audio_codec:
    "audio.truehd_atmos": "9"
    "audio.dtshd_ma": "16"
    "audio.dtsx": "15"
    "audio.dts": "14"
    "audio.truehd": "12"
    "audio.lpcm": "19"
    "audio.wav": "13"
    "audio.flac": "1"
    "audio.ac3": "11"
    "audio.ddp": "10"
    "audio.aac": "6"
    "audio.ogg": "5"
    "audio.mp3": "4"
    "audio.m4a": "17"
    "audio.opus": "18"
    "audio.ape": "2"
    "audio.av3v": "8"
    "audio.other": "7"
    "default": "7"

  resolution:
    "resolution.r1080p": "1"
    "resolution.r1440p": "4"
    "resolution.r2160p": "5"
    "resolution.r4320p": "6"
    "resolution.r720p": "2"
    "resolution.r480p": "3"
    "resolution.other": "7"
    "default": "7"

  team:
    "team.qhstudio": "37"
    "team.chd": "2"
    "team.hds": "1"
    "team.cspt": "38"
    "team.ubweb": "36"
    "team.zmweb": "35"
    "team.hhweb": "34"
    "team.adweb": "31"
    "team.u2": "26"
    "team.opencd": "24"
    "team.beast": "23"
    "team.hdarea": "21"
    "team.ffansdiy": "19"
    "team.cmct": "17"
    "team.ourtv": "16"
    "team.btshd": "15"
    "team.hdhome": "14"
    "team.pterweb": "12"
    "team.hdsweb": "11"
    "team.mweb": "10"
    "team.frds": "8"
    "team.agsvweb": "7"
    "team.starfallweb": "6"
    "team.wiki": "4"
    "team.mysilu": "3"
    "team.other": "5"
    "default": "5"

  tag:
    "tag.DIY": "4"
    "tag.国语": "5"
    "tag.中字": "6"
    "tag.HDR": "7"
    "tag.特效": "8"
    "default": null
